#!/bin/bash
BACKUPFILE=backup-$(date +%m-%d-%Y)
archive=${1:-$BACKUPFILE}
tar cvf - 'find . -mtime -l -type f -print' > $archive.tar
gzip $archive.tar
echo "$PWD backed up in \"$archive.tar.gz\"."
exit 0
