#!/bin/bash
#rpm-check.sh

SUCCESS=0
E_NOARGS=65
if [ -z "$1" ]
then
	echo "Usage:'basename $0' rmp-file"
	exit $E_NOARGS
fi

{
	echo
	echo "Archive Description:"
	rpm -qpi $1
	echo
	echo "Archive Listing:"
	rpm -qul $1
	echo
	rmp -i --test $1
	if [ "$?" -eq $SUCCESS]
	then
		echo "$1 can be installed!"
	else
		echo "$1 cant not be installed"
	fi
	echo
} > "$1.test"

echo "Result of rmp test in file $1.test"
exit 0
