#!/bin/bash
MINPARAMS=10
echo

echo "The name of this script is \"$0\""
echo "The name of this script is \"`basename $0`\""
if [ -n "$1" ]
then
	echo "Parameter #1 is $1"
fi
if [ -n "${10}" ]
then
	echo "Parameter #10 is ${10}"
fi
echo $*
echo $@
echo $#
args=$#
lastarg=${!args}
echo $lastarg
echo ${!#}
exit 0

